teams:
  - name: cacti-contributors-tecnico-lisboa-read-only
    maintainers:
      - RafaelAPB
      - LordKubaya
      - AndreAugusto11
    members:
      - Tomas-Silva2187
      - edsonCVN
      - pandaio22
  - name: cacti-maintainers
    maintainers:
      - petermetz
    members:
      - RafaelAPB
      - AndreAugusto11
      - VRamakrishna
      - outSH
      - sandeepnRES
      - LordKubaya
  - name: cacti-security-administration
    maintainers:
      - RafaelAPB
      - VRamakrishna
    members:
      - LordKubaya
      - AndreAugusto11
      - LordKubaya
      - outSH
      - sandeepnRES
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall

repositories:
  - name: .github
    teams:
      cacti-maintainers: maintain
      lf-staff: admin
    visibility: public

  - name: cacti
    teams:
      cacti-contributors-tecnico-lisboa-read-only: read
      cacti-maintainers: maintain
      cacti-security-administration: admin
    visibility: public

  - name: governance
    teams:
      cacti-maintainers: maintain
      cacti-security-administration: admin
      lf-staff: admin
    visibility: public
